interface TableProps {
  date: string
  title: string
  category: string
  likes: string
  views: string
  author: string
}

export const tableData: TableProps[] = [
  {
    date: '2023/11/20',
    title: 'Local Community Event Success',
    category: 'Events',
    likes: '152',
    views: '3021',
    author: 'Jordan Case',
  },
  {
    date: '2023/11/15',
    title: 'Top 10 Healthy Eating Habits',
    category: 'Health & Wellness',
    likes: '98',
    views: '2763',
    author: 'Alex Smith',
  },
  {
    date: '2023/11/10',
    title: 'Advancements in Renewable Energy',
    category: 'Technology',
    likes: '204',
    views: '4890',
    author: 'Samantha Rays',
  },
  {
    date: '2023/11/05',
    title: 'Interview with a Local Entrepreneur',
    category: 'Business',
    likes: '175',
    views: '3642',
    author: 'Chris Doe',
  },
  {
    date: '2023/11/01',
    title: 'New Art Exhibit Opens Downtown',
    category: 'Culture',
    likes: '89',
    views: '2584',
    author: 'Patricia Kline',
  },

  {
    date: '2023/10/29',
    title: '5 Tips for Sustainable Living',
    category: 'Lifestyle',
    likes: '85',
    views: '1120',
    author: 'Kimberly Santos',
  },
  {
    date: '2023/10/22',
    title: 'The Impact of Social Media on Teens',
    category: 'Psychology',
    likes: '240',
    views: '3500',
    author: 'Luis Perez',
  },
  {
    date: '2023/10/15',
    title: 'Exploring the New Mars Rover Images',
    category: 'Science',
    likes: '190',
    views: '4805',
    author: 'Raj Patel',
  },
  {
    date: '2023/10/08',
    title: 'How to Start Your Own Podcast',
    category: 'Education',
    likes: '105',
    views: '1503',
    author: 'Alicia Yoon',
  },
  {
    date: '2023/10/01',
    title: 'Local Elections: What You Need to Know',
    category: 'Politics',
    likes: '78',
    views: '2654',
    author: 'Mohamed Ali',
  },
  {
    date: '2023/09/24',
    title: 'The Best Hiking Trails for Fall',
    category: 'Travel',
    likes: '132',
    views: '3127',
    author: 'Anita Gomez',
  },
  {
    date: '2023/09/17',
    title: 'Understanding Blockchain Technology',
    category: 'Finance',
    likes: '154',
    views: '2897',
    author: 'Haruto Tanaka',
  },
  {
    date: '2023/09/10',
    title: "A Beginner's Guide to Meditation",
    category: 'Wellness',
    likes: '167',
    views: '4012',
    author: 'Sophie Laurent',
  },
  {
    date: '2023/09/03',
    title: "What's New in the World of Robotics",
    category: 'Innovation',
    likes: '202',
    views: '4579',
    author: 'Ethan Clark',
  },
  {
    date: '2023/08/27',
    title: 'Mastering the Art of French Cooking',
    category: 'Culinary',
    likes: '321',
    views: '5300',
    author: 'Giulia Rossi',
  },

  //
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
  {
    date: '2023/12/29',
    title: "Help. I'm being held hostage",
    category: 'Social Networking',
    likes: '119',
    views: '4556',
    author: 'Miracle Vaccaro',
  },
]
